#####
GET http://localhost:30146
Content-Type: application/json

{
}


#####
POST http://localhost:30146/api/users/signup
Content-Type: application/json

{
    "email": "tabrizi.hasan@yahoo.com",
    "password": "1234week"
}

#####
POST http://localhost:30146/hello
Content-Type: application/json

{
    "email": "tabrizi.mohamadhassan@yahoo.com",
    "password": "1234week"
}