apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - name: auth
      nodePort: 32715
      protocol: TCP
      port: 3001
      targetPort: 3001
      