apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - name: client
      nodePort: 32715
      protocol: TCP
      port: 3001
      targetPort: 3001
      